# -*- coding: utf-8 -*-
"""demo3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16mKAbqwVkPhWInK2cz3favgnSgTKwBWk

### Εκτέλεση του Demo (demo3.py)
Σε αυτό το τελικό βήμα, συνθέτουμε ολόκληρο το σύστημα (Pipeline) πολυδιακριτικής ανάλυσης.
* Διαβάζουμε την ασπρόμαυρη εικόνα `farm.jpg`.
* Αντλούμε τους συντελεστές του βαθυπερατού φίλτρου Daubechies 10 (db10) από τη βιβλιοθήκη `pywt`.
* Παράγουμε την ορθοκανονική συστοιχία (h0, h1, g0, g1).
* Εκτελούμε την 2Δ Ανάλυση, σπάζοντας την εικόνα σε 4 υπο-μπάντες.
* Εκτελούμε την 2Δ Σύνθεση για να ανακατασκευάσουμε την αρχική εικόνα.
* Οπτικοποιούμε τα αποτελέσματα όπως ακριβώς ζητείται από την εκφώνηση, κανονικοποιώντας με τη μέγιστη τιμή φωτεινότητας `L`.
"""

# -*- coding: utf-8 -*-
import cv2
import numpy as np
import matplotlib.pyplot as plt
import pywt
from functions import orthonormalFilterBanks, analysis2d, synthesis2d

def main():
    # 1. Φόρτωση της εικόνας
    img = cv2.imread('farm.jpg', cv2.IMREAD_GRAYSCALE)
    if img is None:
        print("[-] Error: Could not find 'farm.jpg'. Make sure it's in the same folder.")
        return

    x = img.astype(float)
    L = np.max(x) # Μέγιστη τιμή φωτεινότητας για κανονικοποίηση

    # 2. Ανάκτηση του φίλτρου Daubechies 10 (db10)
    db10 = pywt.Wavelet('db10')
    h_base = np.array(db10.dec_lo)

    # 3. Παραγωγή της Ορθοκανονικής Συστοιχίας Φίλτρων
    h0, h1, g0, g1 = orthonormalFilterBanks(h_base)

    # 4. 2Δ Ανάλυση
    print("[+] Executing 2D Analysis...")
    y00, y01, y10, y11 = analysis2d(h0, h1, x)

    # 5. 2Δ Σύνθεση (Ανακατασκευή)
    print("[+] Executing 2D Synthesis...")
    xhat_full = synthesis2d(g0, g1, y00, y01, y10, y11)

    # Crop ώστε να έχει τις διαστάσεις της αρχικής εικόνας
    offset_row = (xhat_full.shape[0] - x.shape[0]) // 2
    offset_col = (xhat_full.shape[1] - x.shape[1]) // 2
    xhat = xhat_full[offset_row : offset_row + x.shape[0], offset_col : offset_col + x.shape[1]]

    # 6. Οπτικοποίηση αποτελεσμάτων
    # Figure 1: Υπο-μπάντες
    plt.figure(1, figsize=(10, 8))
    plt.suptitle("Multiresolution Analysis: 4 Sub-bands")

    bands = [y00, y01, y10, y11]
    titles = ["y00 (LL)", "y01 (LH)", "y10 (HL)", "y11 (HH)"]
    for i in range(4):
        plt.subplot(2, 2, i+1)
        plt.imshow(bands[i] / L, cmap='gray')
        plt.title(titles[i])
        plt.axis("off")

    # Figure 2: Ανακατασκευή
    plt.figure(2, figsize=(8, 10))
    plt.subplot(2, 1, 1)
    plt.imshow(x, cmap='gray')
    plt.title("Original Image (x)")
    plt.axis("off")
    plt.subplot(2, 1, 2)
    plt.imshow(xhat, cmap='gray')
    plt.title("Reconstructed Image (xhat)")
    plt.axis("off")
    plt.tight_layout()
    plt.show()

if __name__ == "__main__":
    main()