# -*- coding: utf-8 -*-
"""demo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qAYS54vpe8aBke29mV5rHAlTWN3lRAG-
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Import ALL functions from your single functions.py file
from functions import (
    myLocalDescriptor,
    myLocalDescriptorUpgrade,
    myDetectHarrisFeatures,
    computeDisparity,
    computeDepth,
    computeDepthMap
)

def main():
    print("="*50)
    print("STARTING DEMO - ASSIGNMENT 2: STEREO VISION")
    print("="*50)

    # 1. Load data
    print("\n[+] Loading images and data...")
    img1 = cv2.imread('im1.png', cv2.IMREAD_GRAYSCALE)
    img2 = cv2.imread('im2.png', cv2.IMREAD_GRAYSCALE)

    if img1 is None or img2 is None:
        print("[-] Error: Could not find 'im1.png' or 'im2.png'.")
        return

    try:
        known_points = np.load('knownpoints.npy')
    except FileNotFoundError:
        print("[-] Error: Could not find 'knownpoints.npy'.")
        return

    # Normalize images to [0, 1] range (required for Harris Corner Detector)
    img1_norm = img1.astype(np.float64) / 255.0
    img2_norm = img2.astype(np.float64) / 255.0


    print("\n" + "-"*40)
    print("DELIVERABLE 1.1.1: Local Descriptors")
    print("-" * 40)

    rhom, rhoM, rhostep, N = 5, 20, 1, 8
    points_to_test = [(100, 100), (200, 200), (202, 202)]

    for p in points_to_test:
        desc_basic = myLocalDescriptor(img1, p, rhom, rhoM, rhostep, N)
        desc_upgrade = myLocalDescriptorUpgrade(img1, p, rhom, rhoM, rhostep, N)

        print(f"\nPoint {p}:")
        print(f" -> Basic Descriptor (Length {len(desc_basic)}):")
        print(np.round(desc_basic, 2))
        print(f" -> Upgraded Descriptor (Length {len(desc_upgrade)}):")
        print(np.round(desc_upgrade, 2))


    print("\n" + "-" * 40)
    print("DELIVERABLE 1.2.1: Harris Corner Detector")
    print("-" * 40)
    print("[+] Running Harris Corner Detector... (Please wait)")

    corners = myDetectHarrisFeatures(img1_norm)
    print(f"[+] Successfully detected {len(corners)} corners in im1.png.")

    # Draw corners and display
    img1_color = cv2.cvtColor(img1, cv2.COLOR_GRAY2BGR)
    for c in corners:
        x, y = c
        cv2.rectangle(img1_color, (x - 2, y - 2), (x + 2, y + 2), (0, 0, 255), -1)

    print("\n>>> Displaying Window 1: Harris Corners")
    print(">>> (PLEASE CLOSE THE IMAGE WINDOW TO CONTINUE THE DEMO) <<<")
    plt.figure(figsize=(10, 7))
    plt.imshow(cv2.cvtColor(img1_color, cv2.COLOR_BGR2RGB))
    plt.title("Detected Harris Corners (im1.png)")
    plt.axis('off')
    plt.show()


    print("\n" + "-" * 40)
    print("PART 2: Stereo Vision & Depth Estimation")
    print("-" * 40)

    # Camera parameters
    D = 144.049       # mm
    f = 4396.869      # px
    doffs = 185.788   # px

    # 1. Calculate for known points
    print("[+] Testing disparity & depth on the first 3 known points:")
    for i in range(3):
        pt = known_points[i]
        x_L, y_L, x_R, y_R, d_est, d_gt = pt

        d_calc = computeDisparity((x_L, y_L), (x_R, y_R))
        z_calc = computeDepth(d_calc, f, D, doffs)

        print(f" - Point {i+1} [xL:{x_L}, xR:{x_R}]:")
        print(f"   Calculated Total Disparity: {d_calc + doffs:.3f}")
        print(f"   Estimated Depth (Z): {z_calc:.2f} mm")

    # 2. Calculate Final Depth Map
    print("\n[+] Computing final Sparse Depth Map...")
    print("[!] (This process includes stereo matching and may take a moment)")

    depth_map = computeDepthMap(img1_norm, img2_norm, f, D, doffs)

    # 3. Display Final Depth Map
    y_idx, x_idx = np.nonzero(depth_map)
    z_vals = depth_map[y_idx, x_idx]

    print("\n>>> Displaying Window 2: Sparse Depth Map")
    plt.figure(figsize=(10, 7))
    plt.imshow(img1, cmap='gray', alpha=0.5)
    sc = plt.scatter(x_idx, y_idx, c=z_vals, cmap='plasma_r', s=15, vmin=1000, vmax=3000)
    plt.colorbar(sc, label='Depth (Z) in mm')
    plt.title("Estimated Sparse Depth Map")
    plt.axis('off')
    plt.show()

    print("\n" + "=" * 50)
    print("Demo completed successfully! :)")
    print("=" * 50)

if __name__ == "__main__":
    main()