# -*- coding: utf-8 -*-
"""functions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ouPJe7Ei3Na1Ez1iySDSajsWM6cTqANE

2η Εργασία στην Ψηφιακή Επεξεργασία Εικόνας-Functions
"""

import numpy as np
import math
import cv2

"""1.1 Helper Function _get_circle_values(): αναλαμβάνει τα μαθηματικά της παρεμβολής."""

def _get_circle_values(I: np.ndarray, px: float, py: float, width: int, height: int, rho: float, N: int, angle_step: float) -> np.ndarray:
    """
    Helper function: Extracts N interpolated values along a circle
    with radius 'rho' centered at (px, py).
    """
    circle_values = np.zeros(N)
    for i in range(N):
        # Calculate coordinates for each point on the circle
        theta = i * angle_step
        cx = px + rho * math.cos(theta)
        cy = py + rho * math.sin(theta)

        # Find the 4 nearest neighbors for bilinear interpolation
        x0 = int(math.floor(cx))
        y0 = int(math.floor(cy))

        x1 = min(x0 + 1, width - 1)
        y1 = min(y0 + 1, height - 1)

        dx = cx - x0
        dy = cy - y0

        # Retrieve pixel intensities
        I00 = float(I[y0, x0])
        I10 = float(I[y0, x1])
        I01 = float(I[y1, x0])
        I11 = float(I[y1, x1])

        # Apply bilinear interpolation formula
        circle_values[i] = (I00 * (1 - dx) * (1 - dy) +
                            I10 * dx * (1 - dy) +
                            I01 * (1 - dx) * dy +
                            I11 * dx * dy)

    return circle_values

"""Συνάρτηση myLocalDescriptor(): Η βασική έκδοση που επιστρέφει τον μέσο όρο."""

def myLocalDescriptor(I: np.ndarray, p: tuple, rhom: float, rhoM: float, rhostep: float, N: int) -> np.ndarray:
    """
    Basic local descriptor: Calculates the mean intensity along concentric circles.
    """
    px, py = p
    height, width = I.shape

    # Check if the largest circle exceeds image boundaries
    if (px - rhoM < 0 or px + rhoM >= width or py - rhoM < 0 or py + rhoM >= height):
        return np.array([])

    # Generate radii array and initialize descriptor
    radii = np.arange(rhom, rhoM, rhostep)
    descriptor = np.zeros(len(radii))
    angle_step = 2 * math.pi / N

    # Calculate the mean value for each circle using the helper function
    for idx, rho in enumerate(radii):
        circle_values = _get_circle_values(I, px, py, width, height, rho, N, angle_step)
        descriptor[idx] = np.mean(circle_values)

    return descriptor

"""Συνάρτηση myLocalDescriptorUpgrade(): Η αναβαθμισμένη έκδοση που επιστρέφει μέσο όρο και τυπική απόκλιση."""

def myLocalDescriptorUpgrade(I: np.ndarray, p: tuple, rhom: float, rhoM: float, rhostep: float, N: int) -> np.ndarray:
    """
    Upgraded local descriptor: Calculates both mean and standard deviation
    along concentric circles for richer texture information.
    """
    px, py = p
    height, width = I.shape

    # Check boundary conditions
    if (px - rhoM < 0 or px + rhoM >= width or py - rhoM < 0 or py + rhoM >= height):
        return np.array([])

    # Initialize descriptor with double the size (mean + std for each circle)
    radii = np.arange(rhom, rhoM, rhostep)
    descriptor = np.zeros(len(radii) * 2)
    angle_step = 2 * math.pi / N

    # Populate the descriptor array using the helper function
    for idx, rho in enumerate(radii):
        circle_values = _get_circle_values(I, px, py, width, height, rho, N, angle_step)

        # Store mean at even indices and standard deviation at odd indices
        descriptor[2*idx] = np.mean(circle_values)
        descriptor[2*idx + 1] = np.std(circle_values)

    return descriptor

"""1.2 Συνάρτηση isCorner(): ελέγχει αν ένα συγκεκριμένο pixel είναι γωνία."""

def isCorner(I: np.ndarray, p: tuple, k: float, Rthres: float) -> bool:
    """
    Checks if a specific pixel p=(x,y) is a corner using a local window.
    Implements the Harris corner response metric R.
    """
    x, y = p
    half_w = 2 # 5x5 local window (2 pixels in each direction)

    # Check if the window exceeds image boundaries
    if x - half_w < 0 or x + half_w >= I.shape[1] or y - half_w < 0 or y + half_w >= I.shape[0]:
        return False

    # Extract local 5x5 patch around the point
    patch = I[y - half_w : y + half_w + 1, x - half_w : x + half_w + 1]

    # Compute Sobel derivatives (Ix, Iy) using 64-bit floats for precision
    Ix = cv2.Sobel(patch, cv2.CV_64F, 1, 0, ksize=3)
    Iy = cv2.Sobel(patch, cv2.CV_64F, 0, 1, ksize=3)

    # Sum of squared derivatives over the window to construct Matrix M
    Sxx = np.sum(Ix ** 2)
    Syy = np.sum(Iy ** 2)
    Sxy = np.sum(Ix * Iy)

    # Calculate Determinant and Trace of Matrix M
    det_M = (Sxx * Syy) - (Sxy ** 2)
    trace_M = Sxx + Syy

    # Corner response function R
    R = det_M - k * (trace_M ** 2)

    # Return True if the response exceeds the defined threshold
    return float(R) > Rthres

"""Συνάρτηση myDetectHarrisFeatures(): κάνει τα "βαριά" μαθηματικά για όλη την εικόνα μονομιάς και επιστρέφει τις συντεταγμένες."""

def myDetectHarrisFeatures(I: np.ndarray) -> np.ndarray:
    """
    Detects Harris corners across the entire image.
    Uses vectorized operations for speed, then filters with isCorner.
    """
    # 1. Compute image derivatives globally
    Ix = cv2.Sobel(I, cv2.CV_64F, 1, 0, ksize=3)
    Iy = cv2.Sobel(I, cv2.CV_64F, 0, 1, ksize=3)

    # Squared derivatives
    Ixx = Ix ** 2
    Iyy = Iy ** 2
    Ixy = Ix * Iy

    # 2. Apply Gaussian blur to simulate the window function 'w'
    Sxx = cv2.GaussianBlur(Ixx, (5, 5), 1.0)
    Syy = cv2.GaussianBlur(Iyy, (5, 5), 1.0)
    Sxy = cv2.GaussianBlur(Ixy, (5, 5), 1.0)

    # 3. Calculate corner response R globally
    det_M = (Sxx * Syy) - (Sxy ** 2)
    trace_M = Sxx + Syy

    k_param = 0.04
    R_map = det_M - k_param * (trace_M ** 2)

    # Define threshold (e.g., 1% of the maximum response)
    Rthres = 0.01 * R_map.max()

    # 4. Non-Maximum Suppression (find local maxima)
    # Dilation replaces each pixel with the maximum in its local 5x5 neighborhood
    R_dilated = cv2.dilate(R_map, np.ones((5, 5)))
    local_maxima = (R_map == R_dilated)

    # Find coordinates that pass the threshold AND are local maxima
    corners_y, corners_x = np.where((R_map > Rthres) & local_maxima)

    # 5. Filter the detected points using the required 'isCorner' function
    final_corners = []
    for x, y in zip(corners_x, corners_y):
        if isCorner(I, (x, y), k_param, Rthres):
            final_corners.append([x, y])

    return np.array(final_corners)

"""2. Συνάρτηση computeDisparity(): υπολογίζει την απλή διαφορά των x-συντεταγμένων μεταξύ της αριστερής και της δεξιάς εικόνας."""

def computeDisparity(p1: tuple, p2: tuple) -> float:
    """
    Computes the raw disparity between matching points in the left (p1)
    and right (p2) images based on their x-coordinates.
    """
    x_left, y_left = p1
    x_right, y_right = p2

    # Calculate horizontal difference
    d = float(x_left - x_right)
    return d

"""Συνάρτηση computeDepth(): εφαρμόζει τη θεμελιώδη στερεοσκοπική εξίσωση z = (f*D) / (d + doffs) για να βρει το βάθος σε mm."""

def computeDepth(d: float, f: float, D: float, doffs: float) -> float:
    """
    Calculates depth (Z) in mm using the focal length, baseline distance,
    and the total disparity (raw disparity + camera offset).
    """
    # Total disparity calculation as per Equation 11
    total_disparity = d + doffs

    # Avoid division by zero
    if total_disparity == 0:
        return 0.0

    # Apply depth equation: Z = (f * D) / d_total
    z = (f * D) / total_disparity
    return float(z)

"""Συνάρτηση computeDepthMap(): συνδυάζει τον Harris Detector και τους Descriptors για να κάνει Stereo Matching και να δημιουργήσει έναν αραιό (sparse) χάρτη βάθους."""

def computeDepthMap(I_left: np.ndarray, I_right: np.ndarray, f: float, D: float, doffs: float) -> np.ndarray:
    """
    Wrapper function that detects corners, matches them using descriptors,
    and populates a sparse depth map.
    """
    # 1. Feature Detection
    c_left = myDetectHarrisFeatures(I_left)
    c_right = myDetectHarrisFeatures(I_right)

    # 2. Descriptor Extraction (using the Upgraded version)
    params = (5, 20, 1, 8) # rhom, rhoM, rhostep, N

    def get_valid_desc(I, corners):
        descs, valid_pts = [], []
        for p in corners:
            d = myLocalDescriptorUpgrade(I, (p[0], p[1]), *params)
            if d.size > 0:
                descs.append(d)
                valid_pts.append(p)
        return descs, valid_pts

    d_l, p_l = get_valid_desc(I_left, c_left)
    d_r, p_r = get_valid_desc(I_right, c_right)

    # 3. Stereo Matching & Depth Mapping
    depth_map = np.zeros_like(I_left, dtype=np.float32)

    for i, desc_l in enumerate(d_l):
        best_dist = float('inf')
        best_idx = -1

        for j, desc_r in enumerate(d_r):
            # Epipolar constraint: check points on similar vertical level
            if abs(p_l[i][1] - p_r[j][1]) <= 10:
                dist = np.linalg.norm(desc_l - desc_r)
                if dist < best_dist:
                    best_dist = dist
                    best_idx = j

        if best_idx != -1:
            disp = computeDisparity(p_l[i], p_r[best_idx])
            if disp > 0: # Ensure point is physically in front
                depth_map[p_l[i][1], p_l[i][0]] = computeDepth(disp, f, D, doffs)

    return depth_map