# -*- coding: utf-8 -*-
"""demo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmTCipfiJufHK_Wi3S590D8sFOL4vluW

Main Block-demo.
"""

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

# Importing all filter and transform functions from your local functions.py
from functions import (
    get_frequency_grid,
    DFT2,
    iDFT2,
    designLowFilter,
    designHighFilter,
    freqFilter,
    designDirectionalFilter,
    designSmoothDirectionalFilter
)

def show_results(title, original, img1, title1, img2, title2):
    """
    Utility to display a 1x3 subplot grid for comparing
    the original image with two filtered versions.
    """
    plt.figure(figsize=(12, 4))
    plt.suptitle(title, fontsize=14)

    plt.subplot(1, 3, 1)
    plt.imshow(original, cmap='gray')
    plt.title("Original Image")
    plt.axis('off')

    plt.subplot(1, 3, 2)
    plt.imshow(img1, cmap='gray')
    plt.title(title1)
    plt.axis('off')

    plt.subplot(1, 3, 3)
    plt.imshow(img2, cmap='gray')
    plt.title(title2)
    plt.axis('off')

    plt.tight_layout()

def plot_directional_bank(f, H_bank, N1, N2, title):
    """
    Displays the output of a directional filter bank in a 3x3 grid.
    Visualizes H0 (low-pass) and H1...Hq (directional components).
    """
    q = H_bank.shape[2] - 1
    plt.figure(figsize=(10, 10))
    plt.suptitle(title, fontsize=16)

    # Process and display the base Low-Pass component (H0)
    g0 = freqFilter(f, H_bank[:, :, 0], N1, N2)
    plt.subplot(3, 3, 1)
    plt.imshow(g0, cmap='gray')
    plt.title("H0: Low-Pass")
    plt.axis('off')

    # Process and display each directional sector (H1 to Hq)
    for i in range(1, q + 1):
        g_i = freqFilter(f, H_bank[:, :, i], N1, N2)
        plt.subplot(3, 3, i + 1)
        plt.imshow(g_i, cmap='gray')
        plt.title(f"H{i}: Directional")
        plt.axis('off')

    plt.tight_layout()

# =========================================================
# MAIN EXECUTION BLOCK
# =========================================================

if __name__ == "__main__":

    # Image Loading and Grayscale Conversion
    # Load the source image and convert it to a 2D float array
    img_path = 'cameraman.png'
    img_pil = Image.open(img_path).convert('L')
    f = np.array(img_pil, dtype=float)
    N1, N2 = f.shape

    # Parameter Initialization
    # Define dynamic cutoff frequencies and directional parameters
    D0_1 = min(N1, N2) / 5
    D0_2 = min(N1, N2) / 2
    D0_dir = min(N1, N2) / 8  # Radial cutoff for directional bank
    q = 8                     # Number of directional sectors
    K = 2                     # Smoothing exponent for angular windowing

    print(f"Dimensions: {N1}x{N2}, D0_1={D0_1:.2f}, D0_2={D0_2:.2f}, D0_dir={D0_dir:.2f}")

    # Ideal Filter Analysis (Low-Pass & High-Pass)
    # Compare sharp frequency truncation across two different cutoff radii
    H_IL1 = designLowFilter(N1, N2, (0, D0_1, None))
    H_IL2 = designLowFilter(N1, N2, (0, D0_2, None))
    g_IL1 = freqFilter(f, H_IL1, N1, N2)
    g_IL2 = freqFilter(f, H_IL2, N1, N2)
    show_results("Ideal Low-Pass Filters", f, g_IL1, "D0 = min/5", g_IL2, "D0 = min/2")

    H_IH1 = designHighFilter(N1, N2, (0, D0_1, None))
    H_IH2 = designHighFilter(N1, N2, (0, D0_2, None))
    g_IH1 = freqFilter(f, H_IH1, N1, N2)
    g_IH2 = freqFilter(f, H_IH2, N1, N2)
    show_results("Ideal High-Pass Filters", f, g_IH1, "D0 = min/5", g_IH2, "D0 = min/2")

    # Gaussian Filter Analysis (Low-Pass & High-Pass)
    # Evaluate smooth frequency transitions to mitigate ringing artifacts
    H_GL1 = designLowFilter(N1, N2, (2, D0_1, None))
    H_GL2 = designLowFilter(N1, N2, (2, D0_2, None))
    g_GL1 = freqFilter(f, H_GL1, N1, N2)
    g_GL2 = freqFilter(f, H_GL2, N1, N2)
    show_results("Gaussian Low-Pass Filters", f, g_GL1, "D0 = min/5", g_GL2, "D0 = min/2")

    H_GH1 = designHighFilter(N1, N2, (2, D0_1, None))
    H_GH2 = designHighFilter(N1, N2, (2, D0_2, None))
    g_GH1 = freqFilter(f, H_GH1, N1, N2)
    g_GH2 = freqFilter(f, H_GH2, N1, N2)
    show_results("Gaussian High-Pass Filters", f, g_GH1, "D0 = min/5", g_GH2, "D0 = min/2")

    # Directional Spectral Decomposition
    # Contrast binary directional masks against windowed smoothing (K=2)
    H_Dir = designDirectionalFilter(N1, N2, D0_dir, q)
    plot_directional_bank(f, H_Dir, N1, N2, "Ideal Directional Filter Bank (q=8)")

    H_SmoothDir = designSmoothDirectionalFilter(N1, N2, D0_dir, q, K)
    plot_directional_bank(f, H_SmoothDir, N1, N2, f"Smoothed Directional Bank (q=8, K={K})")

    # Final Display
    # Render all generated plots for visual comparison
    plt.show()