# -*- coding: utf-8 -*-
"""functions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14bo9ajh5TQpuxQXodlu1Gy6bkHUwbRHt
"""

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

"""get_frequency_grid() function:Helper function to generate centered frequency coordinates and distances. Encapsulates coordinate logic to avoid code duplication across filters."""

def get_frequency_grid(N1: int, N2: int):

    u1 = np.arange(N1)
    u2 = np.arange(N2)
    U1, U2 = np.meshgrid(u1, u2, indexing='ij')

    #centered coordinates(shifted indices)
    u1_bar = U1 - N1/2
    u2_bar = U2 - N2/2

    #calculates Euclidean distance from the spectral center
    D = np.sqrt(u1_bar**2 + u2_bar**2)

    return u1_bar, u2_bar, D

"""DFT() function: Computes the 2D Discrete Fourier Transform of an image"""

def DFT2(f: np.ndarray, N1: int, N2: int, fftshift: int) -> np.ndarray:
    # Create a copy to avoid accidentally modifying the original image
    img = f.copy()

    # Dimension Check: If N1 or N2 are not even, remove the last row/column
    if N1 % 2 != 0:
        N1 -= 1
        img = img[:N1, :]

    if N2 % 2 != 0:
        N2 -= 1
        img = img[:, :N2]

    # Centering trick: Move the DC component to the center if fftshift == 1
    if fftshift == 1:
        # Create grids for the indices n1 and n2
        n1_indices, n2_indices = np.indices((N1, N2))

        # Multiply each pixel by (-1)^(n1+n2)
        # Utilizes the property (-1)^(n1+n2) = 1 if (n1+n2) is even, -1 if odd
        multiplier = (-1) ** (n1_indices + n2_indices)
        img = img * multiplier

    # Compute the 2D DFT using numpy's optimized FFT implementation
    F = np.fft.fft2(img)

    return F

"""iDFT() function: Computes the 2D Inverse Discrete Fourier Transform. Returns the image in the spatial domain."""

def iDFT2(F: np.ndarray, N1: int, N2: int, fftshift: int) -> np.ndarray:

    f_complex = np.fft.ifft2(F) #Computes inverse 2D DFT using numpy's optimized IFFT

    f_real = np.real(f_complex) #Extracts real part to remove negligible imaginary components from floating-point errors

    #Reverses the centering modulation if fftshift was originally applied
    if fftshift == 1:
        n1_indices, n2_indices = np.indices((N1, N2))
        multiplier = (-1) ** (n1_indices + n2_indices)
        f_real = f_real * multiplier

    return f_real

"""designLowFilter() function: Creates a Low-Pass filter (Ideal, Butterworth, or Gaussian)."""

def designLowFilter(N1: int, N2: int, param: tuple) -> np.ndarray:
    filter_type, D0, n = param
    _, _, D = get_frequency_grid(N1, N2)

    if filter_type == 0: # Ideal
        H = (D <= D0).astype(float)
    elif filter_type == 1: # Butterworth
        H = 1.0 / (1.0 + (D / (D0 if D0 != 0 else 1e-8))**(2 * n))
    elif filter_type == 2: # Gaussian
        H = np.exp(-(D**2) / (2 * (D0**2)))
    else:
        raise ValueError("Invalid filter type. Select 0, 1, or 2.")
    return H

"""designHighFilter() function: Creates a High-Pass filter as the complement of a Low-Pass filter."""

def designHighFilter(N1: int, N2: int, param: tuple) -> np.ndarray:
    return 1.0 - designLowFilter(N1, N2, param)

"""freqFilter function: Applies a frequency domain filter H to an input image f. This function implements the convolution theorem by multiplying the image spectrum with the filter transfer function."""

def freqFilter(f: np.ndarray, H: np.ndarray, N1: int, N2: int) -> np.ndarray:

    #Transforms the spatial image to the frequency domain.
    F = DFT2(f, N1, N2, fftshift=1) # We use fftshift=1 to ensure the DC component is at the spectral center,
    # matching the coordinate system used during filter design.

    #Applies the filter H via element-wise (Hadamard) multiplication.
    G = F * H #Both F and H MUST have the same dimensions (N1 x N2).

    #Transforms the filtered spectrum back to the spatial domain.
    g = iDFT2(G, N1, N2, fftshift=1) #We maintain fftshift=1 to correctly reverse the spatial modulation.

    return g

"""designDirectionalFilter() function: Creates a directional filter bank in the frequency domain. Returns a 3D array where H[:,:,0] is a low-pass filter and H[:,:,1...q] are the directional components."""

def designDirectionalFilter(N1: int, N2: int, D0: float, q: int) -> np.ndarray:

    u1_bar, u2_bar, D = get_frequency_grid(N1, N2) # Retrieves centered coordinates and radial distance from the helper

    H = np.zeros((N1, N2, q + 1), dtype=float)  #Initializes the 3D filter bank array (N1 x N2 x q+1)

    #H0: Base Ideal Low-Pass Filter component with cutoff D0
    H[:, :, 0] = (D <= D0).astype(float)

    theta_map = np.arctan2(u2_bar, u1_bar) % np.pi #Computes the angular map and normalize to the range [0, pi)

    #Generates q directional sectors
    for i in range(1, q + 1):
        theta_i = (i - 1) * (np.pi / q) #Calculates the central angle for the i-th directional filter

        #Calculates the shortest angular distance between the map and theta_i
        diff = np.abs(theta_map - theta_i)
        diff = np.minimum(diff, np.pi - diff) #Handles periodicity of directions

        condition = (diff <= (np.pi / (2 * q))) & (D > D0) #Defines the sector: must be within the angular threshold and outside D0

        #Assigns the binary mask to the corresponding bank index
        H[:, :, i] = condition.astype(float)

    return H

"""designSmoothDirectionalFilter() function:Creates a smoothed directional filter bank using a cosine window."""

def designSmoothDirectionalFilter(N1: int, N2: int, D0: float, q: int, K: int) -> np.ndarray:
    #Reuse binary directional masks
    H = designDirectionalFilter(N1, N2, D0, q)

    u1_bar, u2_bar, _ = get_frequency_grid(N1, N2)  #we use underscore (_) for distance D as it is not needed for smoothing logic

    theta_map = np.arctan2(u2_bar, u1_bar) % np.pi

    for i in range(1, q + 1):
        theta_i = (i - 1) * (np.pi / q)
        diff = np.abs(theta_map - theta_i)
        diff = np.minimum(diff, np.pi - diff)

        #Applies smoothing factor (cosine raised to power K)
        smooth_factor = np.cos(diff) ** K
        H[:, :, i] *= smooth_factor

    return H